name: mujoco_export_pipeline
dependencies:
  - python=3.10
  - pip
  - pip:
    - bpy==3.5.0
    - coacd==1.0.0
    - gymnasium
    - ipython
    - mujoco==2.3.5
    - numpy
    - scipy
    - transforms3d
    - trimesh[easy]==3.23.5
