#
# Copyright(c) 2022 Intel. Licensed under the MIT License <http://opensource.org/licenses/MIT>.
#

SPEAR:
  LAUNCH_MODE: "none"
  STANDALONE_EXECUTABLE: "/Users/mroberts/Downloads/SpearSim-Mac-Shipping/SpearSim-Mac-Shipping.app"

  INSTANCE:
    COMMAND_LINE_ARGS:
      resx: 640
      resy: 480

SP_SERVICES:

  LEGACY_SERVICE:
    # AGENT: "SphereAgent" # uncomment when using SphereAgent
    AGENT: "NullAgent" # uncomment when using VehicleAgent
    TASK: "NullTask"
