CORE_UTILS:
  WAIT_FOR_KEYBOARD_INPUT_DURING_INITIALIZATION: false
SIMULATION_CONTROLLER:
  AGENT: 'CameraAgent'
  CAMERA_AGENT:
    ACTION_COMPONENTS:
    - set_location
    - set_rotation
    CAMERA:
      FOV: 90.0
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      RENDER_PASSES:
      - final_color
    CAMERA_ACTOR_NAME: ''
    OBSERVATION_COMPONENTS:
    - camera
    SPAWN_ACTOR_NAME: ''
    SPAWN_LOCATION_X: 0.0
    SPAWN_LOCATION_Y: 0.0
    SPAWN_LOCATION_Z: 0.0
    SPAWN_MODE: specify_pose
    SPAWN_ROTATION_PITCH: 0.0
    SPAWN_ROTATION_ROLL: 0.0
    SPAWN_ROTATION_YAW: 0.0
    STEP_INFO_COMPONENTS: []
  CAMERA_SENSOR:
    READ_SURFACE_DATA: true
    USE_SHARED_MEMORY: true
  CUSTOM_UNREAL_CONSOLE_COMMANDS: []
  IMITATION_LEARNING_TASK:
    AGENT_ACTOR_NAME: ''
    GOAL_ACTOR_NAME: ''
    OBSTACLE_IGNORE_ACTOR_NAMES: []
    TRAJECTORY_LOCATIONS_FILE: ''
    TRAJECTORY_SAMPLING_DEBUG_RENDER: false
    TRAJECTORY_SAMPLING_SEARCH_RADIUS: 10000.0
  IMU_SENSOR:
    DEBUG_RENDER: false
  INTERACTION_MODE: interactive
  IP: 127.0.0.1
  MAP_ID: ''
  NAVMESH:
    AGENT_HEIGHT: 200.0
    AGENT_MAX_SLOPE: 1.0
    AGENT_MAX_STEP_HEIGHT: 1.0
    AGENT_RADIUS: 50.0
    CELL_HEIGHT: 1.0
    CELL_SIZE: 1.0
    DEBUG_NAVIGATION_DATA_FILE: ''
    MAX_SIMPLIFICATION_ERROR: 1.3
    MERGE_REGION_SIZE: 400.0
    MIN_REGION_AREA: 100.0
    TILE_POOL_SIZE: 1024
    TILE_SIZE_UU: 1000.0
    TRAJECTORY_SAMPLING_DEBUG_RENDER: false
    TRAJECTORY_SAMPLING_SEARCH_RADIUS: 0.0
  PHYSICS:
    ENABLE_ENHANCED_DETERMINISM: true
    ENABLE_SUBSTEPPING: true
    MAX_SUBSTEPS: 100
    MAX_SUBSTEP_DELTA_TIME: 0.01
    SIMULATION_STEP_TIME: 0.05
  POINT_GOAL_NAV_TASK:
    AGENT_ACTOR_NAME: ''
    EPISODE_BEGIN:
      AGENT_POSITION_X_MAX: .nan
      AGENT_POSITION_X_MIN: .nan
      AGENT_POSITION_Y_MAX: .nan
      AGENT_POSITION_Y_MIN: .nan
      AGENT_POSITION_Z: .nan
      GOAL_POSITION_X_MAX: .nan
      GOAL_POSITION_X_MIN: .nan
      GOAL_POSITION_Y_MAX: .nan
      GOAL_POSITION_Y_MIN: .nan
      GOAL_POSITION_Z: .nan
      SPAWN_DISTANCE_THRESHOLD: 1.0
    GOAL_ACTOR_NAME: ''
    GOAL_MATERIAL: /Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial
    GOAL_MESH: /Engine/BasicShapes/Cylinder.Cylinder
    OBSTACLE_IGNORE_ACTOR_NAMES: []
    RANDOM_SEED: 0
    REWARD:
      HIT_GOAL: 1.0
      HIT_OBSTACLE: -1.0
  PORT: 30000
  SCENE_ID: ''
  SPHERE_AGENT:
    ACTION_COMPONENTS:
    - add_force
    - add_rotation
    CAMERA:
      FOV: 90.0
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      RENDER_PASSES:
      - final_color
    CAMERA_ACTOR_NAME: ''
    OBSERVATION_COMPONENTS:
    - camera
    - location
    - rotation
    SPAWN_ACTOR_NAME: ''
    SPAWN_LOCATION_X: 0.0
    SPAWN_LOCATION_Y: 0.0
    SPAWN_LOCATION_Z: 0.0
    SPAWN_MODE: specify_pose
    SPAWN_ROTATION_PITCH: 0.0
    SPAWN_ROTATION_ROLL: 0.0
    SPAWN_ROTATION_YAW: 0.0
    SPHERE:
      ANGULAR_DAMPING: 0.0
      LINEAR_DAMPING: 0.0
      MATERIAL: /Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial
      MAX_ANGULAR_VELOCITY: 1.0
      MESH_SCALE_X: 0.5
      MESH_SCALE_Y: 0.5
      MESH_SCALE_Z: 0.5
      STATIC_MESH: /Engine/BasicShapes/Sphere.Sphere
    SPHERE_ACTOR_NAME: ''
    STEP_INFO_COMPONENTS:
    - debug
  TASK: 'NullTask'
  URDFBOT_AGENT:
    ACTION_COMPONENTS:
    - control_joints
    CAMERA:
      FOV: 90.0
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      POSITION_OFFSET_X: 0.0
      POSITION_OFFSET_Y: 0.0
      POSITION_OFFSET_Z: 0.0
      RENDER_PASSES:
      - final_color
    IS_READY_VELOCITY_THRESHOLD: 0.001
    OBSERVATION_COMPONENTS:
    - link_state
    - camera
    SPAWN_ACTOR_NAME: ''
    SPAWN_MODE: specify_pose
    SPAWN_PITCH: 0.0
    SPAWN_POSITION_X: 0.0
    SPAWN_POSITION_Y: 0.0
    SPAWN_POSITION_Z: 0.0
    SPAWN_ROLL: 0.0
    SPAWN_YAW: 0.0
    STEP_INFO_COMPONENTS: []
    URDFBOT_ACTOR_NAME: ''
  VEHICLE_AGENT:
    ACTION_COMPONENTS:
    - set_brake_torques
    - set_drive_torques
    CAMERA:
      FOV: 90.0
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      RENDER_PASSES:
      - final_color
    IS_READY_VELOCITY_THRESHOLD: 0.001
    OBSERVATION_COMPONENTS:
    - camera
    - location
    - rotation
    - wheel_rotation_speeds
    SPAWN_ACTOR_NAME: ''
    SPAWN_LOCATION_X: 0.0
    SPAWN_LOCATION_Y: 0.0
    SPAWN_LOCATION_Z: 0.0
    SPAWN_MODE: specify_pose
    SPAWN_ROTATION_PITCH: 0.0
    SPAWN_ROTATION_ROLL: 0.0
    SPAWN_ROTATION_YAW: 0.0
    STEP_INFO_COMPONENTS:
    - ''
    VEHICLE_ACTOR_NAME: ''
  VISUALIZER:
    ACTOR_NAME: ''
    SPAWN_CAMERA: true
    SPAWN_LOCATION_X: 0.0
    SPAWN_LOCATION_Y: 0.0
    SPAWN_LOCATION_Z: 0.0
    SPAWN_ROTATION_PITCH: 0.0
    SPAWN_ROTATION_ROLL: 0.0
    SPAWN_ROTATION_YAW: 0.0
SPEAR:
  CUSTOM_COMMAND_LINE_ARGUMENTS: []
  GPU_ID: 0
  LAUNCH_MODE: ''
  MAX_NUM_TICKS_AFTER_RESET: 10
  NUM_EXTRA_WARMUP_TICKS: 20
  PAKS_DIR: ''
  RENDER_OFFSCREEN: false
  RPC_CLIENT_INITIALIZE_CONNECTION_MAX_TIME_SECONDS: 120.0
  RPC_CLIENT_INITIALIZE_CONNECTION_SLEEP_TIME_SECONDS: 1.0
  RPC_CLIENT_INTERNAL_RECONNECT_LIMIT: 1
  RPC_CLIENT_INTERNAL_TIMEOUT_SECONDS: 5.0
  STANDALONE_EXECUTABLE: ''
  TEMP_DIR: tmp
  UNREAL_EDITOR_EXECUTABLE: ''
  UNREAL_INTERNAL_LOG_FILE: ''
  UPROJECT: ''
  VULKAN_DEVICE_FILES: ''
  WINDOW_RESOLUTION_X: 1024
  WINDOW_RESOLUTION_Y: 1024
URDFBOT:
  URDFBOT_PAWN:
    CAMERA_COMPONENT:
      FOV: 90.0
      PITCH: 0.0
      POSITION_X: 0.0
      POSITION_Y: 0.0
      POSITION_Z: 50.0
      ROLL: 0.0
      YAW: 0.0
    KEYBOARD_ACTIONS: {}
    URDF_DIR: C:\github\spear\python\spear\urdf
    URDF_FILE: locobot.xml
  URDF_LINK_COMPONENT:
    POSITION_SOLVER_ITERATION_COUNT: 16
    VELOCITY_SOLVER_ITERATION_COUNT: 16
VEHICLE:
  VEHICLE_COMPONENT:
    CHASSIS_HEIGHT: 15.0
    CHASSIS_WIDTH: 15.0
    DRAG_COEFFICIENT: 1.0
    ENABLE_LEGACY_WHEEL_FRICTION: false
    ENABLE_SUSPENSION: true
    ENABLE_WHEEL_FRICTION: true
    MASS: 11.2
  VEHICLE_PAWN:
    ANIM_INSTANCE: /Vehicle/OpenBot/Meshes/ABP_OpenBot.ABP_OpenBot_C
    CAMERA_COMPONENT:
      ASPECT_RATIO: 1.333333
      FOV: 70.0
      LOCATION_X: -60.0
      LOCATION_Y: 0.0
      LOCATION_Z: 30.0
      ROTATION_PITCH: -10.0
      ROTATION_ROLL: 0.0
      ROTATION_YAW: 0.0
    IMU_COMPONENT:
      LOCATION_X: 8.0
      LOCATION_Y: 0.0
      LOCATION_Z: 10.0
      ROTATION_PITCH: 0.0
      ROTATION_ROLL: 0.0
      ROTATION_YAW: 0.0
    SKELETAL_MESH: /Vehicle/OpenBot/Meshes/SK_OpenBot.SK_OpenBot
  VEHICLE_WHEEL:
    FRICTION_FORCE_MULTIPLIER: 3.0
    SPRING_PRELOAD: 0.033
    SPRING_RATE: 0.167
    SUSPENSION_DAMPING_RATIO: 0.5
    SUSPENSION_MAX_DROP: 0.001
    SUSPENSION_MAX_RAISE: 0.001
    WHEEL_MASS: 0.033
    WHEEL_RADIUS: 3.3
    WHEEL_WIDTH: 2.5
