SPEAR:

  # launch unreal engine instance via different modes
  # "standalone_executable", or "uproject", or "running_instance"
  # "standalone_executable" - launches a packaged executable of an Unreal Engine project
  # "uproject" - launches an uproject with Unreal Engine editor executable
  # "running_instance" - connects to an already running instance of Unreal Engine
  LAUNCH_MODE: "standalone_executable"
  
  # If launch_mode is "standalone_exectuable", specify this path to an Unreal application.
  #STANDALONE_EXECUTABLE: "/home/qleboute/Documents/Git/spear/code/unreal_projects/RobotProject/Standalone-Development/LinuxNoEditor/RobotProject.sh"
  STANDALONE_EXECUTABLE: "/home/quentin/Desktop/ISL/spear/code/unreal_projects/RobotProject/Standalone-Development/LinuxNoEditor/RobotProject.sh"


  #TEMP_DIR: "/home/qleboute/Documents/Git/spear/code/unreal_projects/RobotProject/Temp"
  TEMP_DIR: "/home/quentin/Desktop/ISL/spear/code/unreal_projects/RobotProject/Temp"

  VULKAN_DEVICE_FILES: "/usr/share/vulkan/icd.d/nvidia_icd.json"

  # True if unreal engine instance should be launched in headless mode
  # Note: This flag is unused if your launch_mode is "running_instance"
  RENDER_OFFSCREEN: False
  
  # Specify the location of the settings.json parameter file used in the InteriorSim executable. 
  # Allows avoiding the "settings.json not found" error at simulation start:
  #CUSTOM_COMMAND_LINE_ARGUMENTS: ["-RobotSimSettingPath=/home/qleboute/Documents/Git/spear/code/unreal_projects/RobotProject/Standalone-Development/LinuxNoEditor/setting/settings.json"]
  CUSTOM_COMMAND_LINE_ARGUMENTS: []

  # Once a connection has been established, the RPC client will wait for this amount of
  # time before throwing when calling a server function.
  RPC_CLIENT_INITIALIZE_CONNECTION_MAX_TIME_SECONDS: 200.0
  RPC_CLIENT_INITIALIZE_CONNECTION_SLEEP_TIME_SECONDS: 10.0
  RPC_CLIENT_INTERNAL_RECONNECT_LIMIT: 10
  RPC_CLIENT_INTERNAL_TIMEOUT_SECONDS: 200.0
  
SIMULATION_CONTROLLER:
  PORT: 30001 
  TASK: "ImitationLearningTask"
  AGENT: "OpenBotAgent"

  SIMULATION_STEP_TIME_SECONDS: 0.033
  SUBSTEPPING: True
  MAX_SUBSTEP_DELTA_TIME: 0.001
  MAX_SUBSTEPS: 100

  IMITATION_LEARNING_TASK:
    AGENT_ACTOR_NAME: "OpenBotActor"
    GOAL_ACTOR_NAME: ""
    OBSTACLE_IGNORE_ACTOR_NAMES: ["Floor", "obj0", "VehicleMesh"]
    GET_POSITIONS_FROM_TRAJECTORY_SAMPLING: True
    POSITIONS_FILE: ""
    TRAJECTORY_SAMPLING_SEARCH_RADIUS: 10000 # Radius in [m], of the region around the desination coordinates where the goal will be considered as "reached" by the agent. 
    TRAJECTORY_SAMPLING_MAX_ITERS: 10000
    NAVMESH:
      AGENT_RADIUS: 20.0
      AGENT_HEIGHT: 20.0
      AGENT_MAX_STEP_HEIGHT: 2.0
    POSITIONS_FILE: "/home/quentin/Desktop/ISL/spear/code/experimental/openbot/imitation_learning/Trajectories/InitGoalAgentPositions_235388780.csv"
    #POSITIONS_FILE: "/home/qleboute/Documents/Git/spear/code/experimental/openbot/imitation_learning/Trajectories/InitGoalAgentPositions_235388780.csv"

  OPENBOT_AGENT:
    OPENBOT_ACTOR_NAME: "OpenBotActor"
    TRAJECTORY_DATA:
      GOAL_ACTOR_NAME: "GoalActor"
    ACTION_COMPONENTS: ["apply_voltage"] # "apply_voltage", "set_position_xyz_centimeters", "set_orientation_pyr_radians"
    STEP_INFO_COMPONENTS: ["trajectory_data"] # "trajectory_data"
    OBSERVATION_COMPONENTS: ["state_data", "control_data", "camera", "imu", "sonar"] # "state_data", "control_data", "camera", "imu", "sonar"... The type(s) of "camera" sensor is defined by CAMERA_PARAMETERS.RENDER_PASSES
    IS_READY_VELOCITY_THRESHOLD: 0.0
   
    CAMERA:
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 70.0
      RENDER_PASSES: ["final_color", "segmentation", "depth_glsl", "normals"] # "final_color", "segmentation", "depth_glsl", "normals", "lens_distortion" 
      
    NAVMESH:
      AGENT_RADIUS: 17.0
      AGENT_HEIGHT: 20.0
      CELL_SIZE: 1.0
      CELL_HEIGHT: 1.0
      TILE_SIZE_UU: 1
      AGENT_MAX_SLOPE: 0.1
      AGENT_MAX_STEP_HEIGHT: 2.0
      MERGE_REGION_SIZE: 0.0
      MIN_REGION_AREA: 400.0
      MAX_SIMPLIFICATION_ERROR: 1.3
      WORLD_BOUND_TAG_NAMES: ["architecture", "furniture"]
  
  VISUALIZER:
    ACTOR_NAME: "OpenBotActor"
    SPAWN_CAMERA: True
    SPAWN_CAMERA_POSITION_X: -50.0
    SPAWN_CAMERA_POSITION_Y: 0.0
    SPAWN_CAMERA_POSITION_Z: 40.0
    SPAWN_CAMERA_ORIENTATION_PITCH: -35.0
    SPAWN_CAMERA_ORIENTATION_YAW: 0.0
    SPAWN_CAMERA_ORIENTATION_ROLL: 0.0
  
  SONAR_SENSOR:
    NUM_RAYS: 11
    DEBUG_RENDER: True
    MAX_REFLECTION_ANGLE: 45.0
    HORIZONTAL_FOV: 30.0
    VERTICAL_FOV: 10.0
    RANGE:
      MIN: 0.01
      MAX: 10.0
    NOISE_STD: 0.0

  IMU_SENSOR:
    DEBUG_RENDER: True
    ACCELEROMETER_NOISE_STD: 
      X: 0.0
      Y: 0.0
      Z: 0.0
    GYROSCOPE_NOISE_STD: 
      X: 0.0
      Y: 0.0
      Z: 0.0
    GYROSCOPE_BIAS: 
      X: 0.0
      Y: 0.0
      Z: 0.0
      
OPENBOT:
  OPENBOT_PAWN:
    SKELETAL_MESH: "/OpenBot/V0/Meshes/OpenBot_V0_Mesh.OpenBot_V0_Mesh"
    ANIM_INSTANCE: "/OpenBot/V0/Meshes/OpenBot_V0_Animation.OpenBot_V0_Animation_C"

    MOTOR_VELOCITY_CONSTANT: 65.89 # Velocity constant of the OpenBot motors
    GEAR_RATIO: 50.0               # Gear ratio of the OpenBot motors

    BATTERY_VOLTAGE: 12.0          # Voltage of the battery powering the OpenBot [V]
    CONTROL_DEAD_ZONE: 2.5         # Absolute duty cycle (in the ACTION_SCALE range) below which a command does not produces any torque on the vehicle
    MOTOR_TORQUE_MAX: 0.19         # Motor maximal torque [N.m]
    ELECTRICAL_RESISTANCE: 0.5     # Motor winding electrical resistance [Ohms]
    ELECTRICAL_INDUCTANCE: 0.5     # Motor winding electrical inductance [Henry]
    
    ACTION_SCALE: 255              # Action scaling factor

    VEHICLE_COMPONENT:
      DRAG_COEFFICIENT: 1.0        # DragCoefficient of the vehicle chassis
      CHASSIS_WIDTH: 15.0          # Chassis width used for drag force computation in [cm]
      CHASSIS_HEIGHT: 15.0         # Chassis height used for drag force computation in [cm]
      MOTOR_MAX_RPM: 20000.0       # Max RPM for engine

    CAMERA_COMPONENT:
      POSITION_X: 5.0
      POSITION_Y: 5.0
      POSITION_Z: 5.0
      ROLL: 0.0
      YAW: 0.0
      PITCH: 0.0
      FOV: 70.0
    
    IMU_COMPONENT:
      POSITION_X: 5.0
      POSITION_Y: 0.0
      POSITION_Z: 5.0
      ROLL: 0.0
      YAW: 0.0
      PITCH: 0.0
      
    SONAR_COMPONENT:
      POSITION_X: 10.0
      POSITION_Y: 0.0
      POSITION_Z: -1.5
      ROLL: 0.0
      YAW: 0.0
      PITCH: 0.0

  OPENBOT_WHEEL:
    AFFECTED_BY_HANDBRAKE: True
    SHAPE_RADIUS: 3.3              # Radius of the wheel in [m]
    SHAPE_WIDTH: 1.5               # Width of the wheel in [m]
    STEER_ANGLE: 0.0
    SUSPENSION_MAX_RAISE: 0.0      # How far the wheel can go above the resting position in [m]
    SUSPENSION_MAX_DROP: 0.0       # How far the wheel can drop below the resting position in [m]
    MASS: 0.033                    # Mass of this wheel in [kg]
