INTERIORSIM:
  LAUNCH_MODE: "standalone_executable"
  STANDALONE_EXECUTABLE: "/home/qleboute/Documents/Git/interiorsim/code/unreal_projects/RobotProject/dist/LinuxNoEditor/RobotProject.sh"
  TEMP_DIR: "/home/qleboute/Documents/Git/interiorsim/code/unreal_projects/RobotProject/Temp"
  RPC_CLIENT_INTERNAL_TIMEOUT_SECONDS: 30.0
  CUSTOM_COMMAND_LINE_ARGUMENTS:
    - "/home/qleboute/Documents/Git/interiorsim/code/unreal_projects/RobotProject/Plugins/RobotSim/setting/settings.json"
SIMULATION_CONTROLLER:
  #AGENT_CONTROLLER_NAME: "SphereAgentController"
  TASK_NAME: "PointGoalNavigation"
  POINT_GOAL_NAV_TASK:
    RANDOM_SEED: 123
