INTERIOR_SIM_BRIDGE:
  
  # If set to True, the actor provides egocentric visual observations:
  USE_IMAGE_OBSERVATIONS: True
  
  # Allows behavior specialization of the InteriorSimBridge classes:
  # - "yaw-x-y" the observation vector is set to be the vehicle's yaw, x position and y position in the world frame.
  # - "dist-sin-cos" the observation vector is set to be the vehicle's distance to the goal, the cos and sin components of the relative yaw between the vehicle's front (x) axis and the vector connecting the vehicle to its goal.
  OBSERVATION_VECTOR: "yaw-x-y"


  
