SIMULATION_CONTROLLER:
  SIMULATION_STEP_TIME_SECONDS: 0.1
  AGENT_CONTROLLER_NAME: ""
  TASK_NAME: ""

  SPHERE_AGENT_CONTROLLER:    
    OBSERVATION_MODE: "mixed" # "mixed" or "physical"
    VISUALIZATION_MODE: "observation" # "debug" or "observation"
    ACTOR_NAME: "Sphere_2"
    OBSERVATION_CAMERA_NAME: "ObservationCameraActor"
    GOAL_NAME: "Cone_5"
    DEBUG_CAMERA_NAME: "DebugCameraActor"
    SPHERE:
      KEYBOARD_INPUT_FORCE_SCALE: 1000000.0
      MASS_SCALE: 1.0
      MAX_ANGULAR_VELOCITY: 1.0
      LINEAR_DAMPING: 0.1
      ANGULAR_DAMPING: 0.1
    DEBUG_CAMERA:
      SET_POSE: True
      POSITION_X: -250.0
      POSITION_Y: -155.0
      POSITION_Z: 200.0
      PITCH: -90.0
      YAW: 0.0
      ROLL: 0.0
    OBSERVATION_CAMERA:
      POSITION_OFFSET_X: 0.0
      POSITION_OFFSET_Y: 0.0
      POSITION_OFFSET_Z: 5.0
    OBSERVATION:
      OFFSET_TO_GOAL_SCALE: 0.01
      LINEAR_VELOCITY_SCALE: 0.01
      YAW_SCALE: 1.0
    MIXED_MODE:
      IMAGE_HEIGHT: 128
      IMAGE_WIDTH: 128
      ACTION_APPLY_FORCE_SCALE: 1000.0
      ACTION_ROTATE_OBSERVATION_CAMERA_SCALE: 10.0
    PHYSICAL_MODE:
      ACTION_APPLY_FORCE_SCALE: 1000.0

  POINT_GOAL_NAV_TASK:
    GOAL_NAME: "Cone_5"
    ACTOR_NAME: "Sphere_2"
    RANDOM_SEED: 0
    REWARD:
      HIT_GOAL: 100.0
      HIT_OBSTACLE: -100.0
      DISTANCE_TO_GOAL_SCALE: 100000.0
    EPISODE_BEGIN:
      SPHERE_POSITION_X_MIN: -300.0
      SPHERE_POSITION_X_MAX: -220.0
      SPHERE_POSITION_Y_MIN: -200.0
      SPHERE_POSITION_Y_MAX: -120.0
      SPHERE_POSITION_Z: 5.0
      CONE_POSITION_X_MIN: -300.0
      CONE_POSITION_X_MAX: -220.0
      CONE_POSITION_Y_MIN: -200.0
      CONE_POSITION_Y_MAX: -120.0
      CONE_POSITION_Z: 5.0
      SPAWN_DISTANCE_THRESHOLD: 20.0
      OBSERVATION_CAMERA_POSITION_OFFSET_X: 0.0
      OBSERVATION_CAMERA_POSITION_OFFSET_Y: 0.0
      OBSERVATION_CAMERA_POSITION_OFFSET_Z: 5.0
    OBSTACLE_IGNORE_ACTOR_NAMES: ["Architecture_SMid0_PMid0_INSTid1227_obj19", "6KAPD2ZVAZSUSPTUKE888888_SMid116_PMid1009_INSTid1080_obj0_0"]

  DEBUG_AGENT_CONTROLLER:
    ACTOR_NAME: "Sphere"
    FIRST_OBSERVATION_CAMERA_NAME: "FirstObservationCamera"
    FIRST_OBSERVATION_CAMERA_HEIGHT: 512
    FIRST_OBSERVATION_CAMERA_WIDTH: 512
    SECOND_OBSERVATION_CAMERA_NAME: "SecondObservationCamera"
    SECOND_OBSERVATION_CAMERA_HEIGHT: 512
    SECOND_OBSERVATION_CAMERA_WIDTH: 512
