SIMULATION_CONTROLLER:
  SIMULATION_STEP_TIME_SECONDS: 0.1
  AGENT_CONTROLLER_NAME: ""

  SPHERE_AGENT_CONTROLLER:
    ACTOR_NAME: "SphereActor"
    OBSERVATION_CAMERA_NAME: "FirstObservationCamera"
    OBSERVATION_CAMERA_HEIGHT: 512
    OBSERVATION_CAMERA_WIDTH: 512

  DEBUG_AGENT_CONTROLLER:
    ACTOR_NAME: "SphereActor"
    FIRST_OBSERVATION_CAMERA_NAME: "FirstObservationCamera"
    FIRST_OBSERVATION_CAMERA_HEIGHT: 512
    FIRST_OBSERVATION_CAMERA_WIDTH: 512
    SECOND_OBSERVATION_CAMERA_NAME: "SecondObservationCamera"
    SECOND_OBSERVATION_CAMERA_HEIGHT: 512
    SECOND_OBSERVATION_CAMERA_WIDTH: 512
