SIMULATION_CONTROLLER:
  IP: "127.0.0.1"
  PORT: 30000
  LEVEL_PATH: "/Game/Maps"
  LEVEL_PREFIX: "Map_"
  LEVEL_ID: ""

  SIMULATION_STEP_TIME_SECONDS: 0.033
  SUBSTEPPING: True
  MAX_SUBSTEP_DELTA_TIME: 0.001
  MAX_SUBSTEPS: 100
  
  TASK_NAME: ""
  AGENT_CONTROLLER_NAME: ""
  CUSTOM_UNREAL_CONSOLE_COMMANDS: []

  POINT_GOAL_NAV_TASK:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    RANDOM_SEED: 0
    REWARD:
      HIT_GOAL: 1.0
      HIT_OBSTACLE: -1.0
      DISTANCE_TO_GOAL_SCALE: 1.0
    EPISODE_BEGIN:
      AGENT_POSITION_X_MIN: .NAN
      AGENT_POSITION_X_MAX: .NAN
      AGENT_POSITION_Y_MIN: .NAN
      AGENT_POSITION_Y_MAX: .NAN
      AGENT_POSITION_Z: .NAN
      GOAL_POSITION_X_MIN: .NAN
      GOAL_POSITION_X_MAX: .NAN
      GOAL_POSITION_Y_MIN: .NAN
      GOAL_POSITION_Y_MAX: .NAN
      GOAL_POSITION_Z: .NAN
      SPAWN_DISTANCE_THRESHOLD: 1.0
    OBSTACLE_IGNORE_ACTOR_NAMES: []

  IMITATION_LEARNING_TASK:
    TRAJECTORY_FILE: ""
    RANDOM_SPAWN_TRAJ: True
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    RANDOM_SEED: 0
    REWARD:
      HIT_GOAL: 1.0
      HIT_OBSTACLE: -1.0
      DISTANCE_TO_GOAL_SCALE: 1.0
    EPISODE_BEGIN:
      AGENT_POSITION_X_MIN: .NAN
      AGENT_POSITION_X_MAX: .NAN
      AGENT_POSITION_Y_MIN: .NAN
      AGENT_POSITION_Y_MAX: .NAN
      AGENT_POSITION_Z: .NAN
      GOAL_POSITION_X_MIN: .NAN
      GOAL_POSITION_X_MAX: .NAN
      GOAL_POSITION_Y_MIN: .NAN
      GOAL_POSITION_Y_MAX: .NAN
      GOAL_POSITION_Z: .NAN
      SPAWN_DISTANCE_THRESHOLD: 1.0
    OBSTACLE_IGNORE_ACTOR_NAMES: []
    TARGET_RADIUS: 10000
    ACCEPTANCE_RADIUS: 0.1
    PATH_WEIGHT_DIST: 1.0
    PATH_WEIGHT_NUM_WAYPOINTS: 1.0
    MAX_ITER_REPLAN: 10000
    AGENT_POSITION_Z_MIN: 5.0
    AGENT_POSITION_Z_MAX: 20.0
    PATH_TRAJECTORY_PAIRS: ""
    AUTOPILOT:
      # PID proportional gain for the autopilot
      PROPORTIONAL_GAIN_HEADING: 5.25
  
      # PID derivative gain for the autopilot
      DERIVATIVE_GAIN_HEADING: 0.5
  
      # PID proportional gain for the autopilot
      PROPORTIONAL_GAIN_DIST: 4.0
  
      # PID derivative gain for the autopilot
      DERIVATIVE_GAIN_DIST: -0.1
  
      # Angular range within which the vehicle moves forward to the target in [rad]
      FORWARD_MIN_ANGLE: 0.5
  
      # Saturates the ammount of linar (resp. angular) command before merging them into left/right wheels command
      CONTROL_SATURATION: 0.9

  OPENBOT_AGENT_CONTROLLER:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    ACTION_COMPONENTS: ["apply_voltage"] # "apply_voltage", "set_position_xyz_centimeters", "set_orientation_pyr_radians"
    STEP_INFO_COMPONENTS: ["trajectory_data"] # "trajectory_data"
    OBSERVATION_COMPONENTS: ["state_data", "control_data", "camera", "imu", "sonar"] # "state_data", "control_data", "camera", "imu", "sonar"... The type(s) of "camera" sensor is defined by CAMERA_PARAMETERS.RENDER_PASSES
    WORLD_BOUND_TAG_NAMES: ["architecture", "furniture"]
    AGENT_READY_VELOCITY_THRESHOLD: 0.0
    CAMERA_PARAMETERS:
      IMAGE_HEIGHT: 128
      IMAGE_WIDTH: 128
      FOV: 90.0                   # Field of view of the smartphone camera in [deg]
      MOTION_BLUR_AMOUNT: 0.0     # Strength of motion blur, 0:off, should be renamed to intensity
      MOTION_BLUR_MAX: 0.0        # Max distortion caused by motion blur, in percent of the screen width, 0:off
      POST_PROC_BLEND_WEIGHT: 0.0 # Range (0.0, 1.0) where 0 indicates no effect, 1 indicates full effect
      RENDER_PASSES: ["final_color", "segmentation", "depth_glsl"] # "final_color", "segmentation", "depth_glsl", "normals", "lens_distortion" 
    SONAR_PARAMETERS:
      MAX_REFLECTION_ANGLE: 45.0
      HORIZONTAL_FOV: 30.0
      VERTICAL_FOV: 10.0
      DEBUG: False
      RANGE:
        MIN: 0.01
        MAX: 2.5
      NOISE_STD: 0.0
    IMU_PARAMETERS:
      DEBUG: False
      ACCELEROMETER_NOISE_STD: 
        X: 0.0
        Y: 0.0
        Z: 0.0
      GYROSCOPE_NOISE_STD: 
        X: 0.0
        Y: 0.0
        Z: 0.0
      GYROSCOPE_BIAS: 
        X: 0.0
        Y: 0.0
        Z: 0.0
    NAVMESH:
      AGENT_RADIUS: 20.0
      AGENT_HEIGHT: 20.0
      CELL_SIZE: 1.0
      CELL_HEIGHT: 1.0
      TILE_SIZE_UU: 300
      AGENT_MAX_SLOPE: 0.1
      AGENT_MAX_STEP_HEIGHT: 2.0
      MERGE_REGION_SIZE: 0.0
      MIN_REGION_AREA: 400.0
      MAX_SIMPLIFINCATION_ERROR: 1.3

  SPHERE_AGENT_CONTROLLER:
    OBSERVATION_MODE: "mixed" # "mixed" or "physical"
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    SPHERE:
      MASS_SCALE: 1.0
      MAX_ANGULAR_VELOCITY: 1.0
      LINEAR_DAMPING: 0.0
      ANGULAR_DAMPING: 0.0
    MIXED_MODE:
      OBSERVATION_CAMERA_ACTOR_NAME: ""
      SET_OBSERVATION_CAMERA_POSE_EGOCENTRIC: True
      IMAGE_HEIGHT: 128
      IMAGE_WIDTH: 128
      ACTION_APPLY_FORCE_SCALE: 1.0
      ACTION_ROTATE_OBSERVATION_CAMERA_SCALE: 1.0
      OBSERVATION_CAMERA_POSITION_OFFSET_X: 0.0
      OBSERVATION_CAMERA_POSITION_OFFSET_Y: 0.0
      OBSERVATION_CAMERA_POSITION_OFFSET_Z: 1.0
      YAW_SCALE: 1.0
      OFFSET_TO_GOAL_SCALE: 1.0
      LINEAR_VELOCITY_SCALE: 1.0
      RENDER_PASSES: ["final_color"] # "final_color", "segmentation", "depth_glsl", "normals", "lens_distortion" 
    PHYSICAL_MODE:
      ACTION_APPLY_FORCE_SCALE: 1.0
      OFFSET_TO_GOAL_SCALE: 1.0
      LINEAR_VELOCITY_SCALE: 1.0

  CAMERA_AGENT_CONTROLLER:
    CAMERA_ACTOR_NAME: ""
    RENDER_PASSES: ["final_color"]
    CAMERA_PARAMETERS:
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 90.0
      FINAL_COLOR_AUTO_EXPOSURE_OVERRIDE_SPEED_UP: False
      FINAL_COLOR_AUTO_EXPOSURE_SPEED_UP: 0.0
      FINAL_COLOR_AUTO_EXPOSURE_OVERRIDE_SPEED_DOWN: False
      FINAL_COLOR_AUTO_EXPOSURE_SPEED_DOWN: 0.0
    NAVMESH:
      AGENT_HEIGHT: 1.0
      AGENT_RADIUS: 1.0
      CELL_SIZE: 1.0
      CELL_HEIGHT: 1.0
      AGENT_MAX_STEP_HEIGHT: -1.0
      AGENT_MAX_SLOPE: 1.0
      MERGE_REGION_SIZE: 0.0
      MIN_REGION_AREA: 0.0
      TILE_SIZE_UU: 1
      NAV_MODIFIER_OFFSET_X: 0.0
      NAV_MODIFIER_OFFSET_Y: 0.0
      NAV_MODIFIER_OFFSET_Z: 0.0
      WORLD_BOUND_TAG_NAMES: ["architecture", "furniture"]
      EXPORT_NAV_DATA_OBJ: False
      EXPORT_NAV_DATA_OBJ_DIR: ""

  VISUALIZER:
    CAMERA_ACTOR_NAME: ""
    SET_CAMERA_POSE: False
    CAMERA_POSITION_X: .NAN
    CAMERA_POSITION_Y: .NAN
    CAMERA_POSITION_Z: .NAN
    CAMERA_PITCH: 0.0
    CAMERA_YAW: 0.0
    CAMERA_ROLL: 0.0

  SONAR_SENSOR:
    N_RAYS: 11
    DEBUG: True
    MAX_REFLECTION_ANGLE: 45.0
    HORIZONTAL_FOV: 30.0
    VERTICAL_FOV: 10.0
    RANGE:
      MIN: 0.01
      MAX: 10.0
    NOISE_STD: 0.0

  IMU_SENSOR:
    DEBUG: True
    ACCELEROMETER_NOISE_STD: 
      X: 0.0
      Y: 0.0
      Z: 0.0
    GYROSCOPE_NOISE_STD: 
      X: 0.0
      Y: 0.0
      Z: 0.0
    GYROSCOPE_BIAS: 
      X: 0.0
      Y: 0.0
      Z: 0.0

  # We have found these values achieve a good trade-off between image quality and
  # rendering speed. When Unreal defines ClampMin/ClampMax values, it will clamp
  # those values in the engine. When Unreal defines UIMin/UIMax vales, it will
  # only clamp those values values in the editor.
  CAMERA_SENSOR:
    FINAL_COLOR_OVERRIDE_AUTO_EXPOSURE_SPEED_UP: true
    FINAL_COLOR_AUTO_EXPOSURE_SPEED_UP: 9999.0                          # ClampMin=0.02, UIMax=20.0
    FINAL_COLOR_OVERRIDE_AUTO_EXPOSURE_SPEED_DOWN: true
    FINAL_COLOR_AUTO_EXPOSURE_SPEED_DOWN: 9999.0                        # ClampMin=0.02, UIMax=20.0
    FINAL_COLOR_OVERRIDE_INDIRECT_LIGHTING_INTENSITY: true
    FINAL_COLOR_INDIRECT_LIGHTING_INTENSITY: 0.0                        # set to 0.0 to use raytracing global illumination
    FINAL_COLOR_USE_RAYTRACING_IF_ENABLED: true                         # set to true to use UE Raytracing features
    FINAL_COLOR_OVERRIDE_RAYTRACING_GI: true
    FINAL_COLOR_RAYTRACING_GI_TYPE: "BruteForce"                        # set to "BruteForce" when using Raytracing
    FINAL_COLOR_OVERRIDE_RAYTRACING_GI_MAX_BOUNCES: true
    FINAL_COLOR_RAYTRACING_GI_MAX_BOUNCES: 4                            # ClampMin=1, ClampMax=64
    FINAL_COLOR_OVERRIDE_RAYTRACING_GI_SAMPLES_PER_PIXEL: true
    FINAL_COLOR_RAYTRACING_GI_SAMPLES_PER_PIXEL: 16                     # ClampMin=1, ClampMax=64
    FINAL_COLOR_OVERRIDE_RAYTRACING_AO: True
    FINAL_COLOR_RAYTRACING_AO: 1                                        # set to 1 to enable and 0 to disable
    FINAL_COLOR_OVERRIDE_RAYTRACING_AO_SAMPLES_PER_PIXEL: true
    FINAL_COLOR_RAYTRACING_AO_SAMPLES_PER_PIXEL: 8                      # ClampMin=1, ClampMax=64
    FINAL_COLOR_OVERRIDE_RAYTRACING_AO_INTENSITY: true
    FINAL_COLOR_RAYTRACING_AO_INTENSITY: 0.8                            # ClampMin=0.0, ClampMax=1.0
    FINAL_COLOR_OVERRIDE_RAYTRACING_AO_RADIUS: true
    FINAL_COLOR_RAYTRACING_AO_RADIUS: 4000.0                            # ClampMin=0.0, ClampMax=10000.0
    FINAL_COLOR_OVERRIDE_REFLECTIONS_TYPE: true
    FINAL_COLOR_REFLECTIONS_TYPE: "RayTracing"                          # set to "RayTracing" when using Raytracing
    FINAL_COLOR_OVERRIDE_RAYTRACING_REFLECTIONS_MAX_BOUNCES: true
    FINAL_COLOR_RAYTRACING_REFLECTIONS_MAX_BOUNCES: 2                   # ClampMin=1, ClampMax=64
    FINAL_COLOR_OVERRIDE_RAYTRACING_REFLECTIONS_MAX_ROUGHNESS: true 
    FINAL_COLOR_RAYTRACING_REFLECTIONS_MAX_ROUGHNESS: 0.4               # ClampMin=0.01, ClampMax=1.0
    FINAL_COLOR_OVERRIDE_RAYTRACING_REFLECTIONS_SAMPLES_PER_PIXEL: true
    FINAL_COLOR_RAYTRACING_REFLECTIONS_SAMPLES_PER_PIXEL: 8             # ClampMin=1, ClampMax=64
    FINAL_COLOR_OVERRIDE_RAYTRACING_REFLECTIONS_TRANSLUCENCY: true
    FINAL_COLOR_RAYTRACING_REFLECTIONS_TRANSLUCENCY: 1                  # set to 1 to enable and 0 to disable
    FINAL_COLOR_SET_AMBIENT_OCCLUSION: true                             # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_CAMERA_IMPERFECTIONS: true                          # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_COLOR_GRADING: true                                 # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_DEPTH_OF_FIELD: true                                # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_DISTANCE_FIELD_AO: true                             # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_EYE_ADAPTATION: true                                # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_GRAIN: true                                         # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_INDIRECT_LIGHTING_CACHE: true                       # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_LENS_FLARES: true                                   # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_LIGHT_SHAFTS: true                                  # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_SCREEN_SPACE_REFLECTIONS: true                      # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_SEPARATE_TRANSLUCENCY: true                         # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_TEMPORAL_AA: true                                   # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_VIGNETTE: true                                      # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_ANTI_ALIASING: true
    FINAL_COLOR_SET_RAYTRACED_DISTANCE_FIELD_SHADOWS: true
    FINAL_COLOR_SET_DYNAMIC_SHADOWS: true
